providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311Full", "gcc"]

[phases.install]
cmds = [
  "python -m ensurepip --default-pip",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "python manage.py migrate && python manage.py createcachetable && python manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
