databases:
  - name: mediascope-db
    databaseName: mediascope
    user: mediascope
    plan: free

services:
  - type: web
    name: mediascope
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mediascope-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: WEB_CONCURRENCY
        value: "4"
